---
all:
  children:
    k8s:
      children:
        master:
          hosts:
            k8s-master:
              ansible_host: 192.168.13.11
              ansible_user: ubuntu
              ansible_password: password
        worker:
          hosts:
            k8s-node1:
              ansible_host: 192.168.13.12
              ansible_user: ubuntu
              ansible_password: password
            k8s-node2:
              ansible_host: 192.168.13.13
              ansible_user: ubuntu
              ansible_password: password
