---
- name: Check cmdline.txt
  shell: "cat /boot/firmware/cmdline.txt"
  changed_when: false
  register: cmdline

- block:
  - name: Set cgroups int cmdline.txt
    template:
      src: cmdline.txt.j2
      dest: /boot/firmware/cmdline.txt
      owner: root
      group: root
      mode: 0755
    become: true

  - name: reboot node when update cmdline.txt
    reboot:
    become: true

  when:
    - "'cgroup' not in cmdline.stdout"

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: yes

- name: set hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ item.regexp }}'
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^127.0.1.1',    line: "127.0.1.1  {{ inventory_hostname }}" }
    - { regexp: "192.168.13.11", line: "192.168.13.11  k8s-master" }
    - { regexp: "192.168.13.12", line: "192.168.13.12  k8s-node1" }
    - { regexp: "192.168.13.13", line: "192.168.13.13  k8s-node2" }
  become: true

- name: Set iptables
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy
  become: yes

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  become: yes

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  become: yes

- name: install common packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python-dev
    - python2
    - python3-pip
  become: true

- get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    dest: /tmp/get-pip.py

- command: python2 /tmp/get-pip.py
  become: true