---
- name: get nodes
  command: kubectl get nodes
  register: get_nodes
  delegate_to: "{{ groups['master'][0] }}"
  changed_when: false

- block:
  - name: Generate join token
    command: kubeadm token create --print-join-command
    register: kubeadm_join_cmd
    delegate_to: "{{ groups['master'][0] }}"
  
  - name: Get kubectl config
    command: kubectl config view --raw
    register: kubectl_config
    delegate_to: "{{ groups['master'][0] }}"

  - name: Set kubeadm join command
    set_fact:
      kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

  - name: Join node to k8s cluster
    command: "{{ kubeadm_join }}"
    become: true

  - name: Set kubectl files
    file:
      path:  "{{ item.path }}"
      state: "{{ item.state }}"
    with_items:
      - { path: /home/ubuntu/.kube , state: directory }
      - { path: /home/ubuntu/.kube/config , state: touch }
  
  - name: Set kubectl config
    blockinfile:
      dest: /home/ubuntu/.kube/config
      content: "{{ kubectl_config.stdout }}"

  - name: set worker label to node
    command: kubectl label node "{{ inventory_hostname }}" node-role.kubernetes.io/worker=

  when:
    - "inventory_hostname not in get_nodes.stdout"