---
- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: true

- apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: true

- name: check hold package
  command: apt-mark showhold
  register: holds
  changed_when: false

- name: hold docker version
  shell: apt-mark hold docker-ce
  become: true
  when:
    - holds.stdout.find('docker-ce') == -1

- name: append docker group
  user:
    name: pi
    groups: docker
    append: true
  become: true